.ci_templates_repo: &ci_templates
  project: &ci_templates_project 'util8860911/ci/templates'
  ref: &ci_templates_version 'v1.0.7'

include:
  - { <<: *ci_templates, file: /stages.yml }
  - { <<: *ci_templates, file: /go.yml }
  - { <<: *ci_templates, file: /docker.yml }
  - { <<: *ci_templates, file: /deploy.yml }

variables:
  DOCKER_IMAGE: images.registry.twcstorage.ru/util/notification-api
  DEPLOY_SERVICE_NAME: notification-api
  GO_MAIN_PATH: cmd/main.go
  GO_BUILD_ARCH: arm64

docker:
  extends: .docker_kaniko

deploy:
  extends: .deploy_agent
