stages:
  - build
  - test
  - docker

variables:
  GOPATH: /go
  GOPROXY: direct
  DOCKER_IMAGE: images.registry.twcstorage.ru/util/notification-api

build:
  stage: build
  image: golang:1.25.11
  script:
    - GOOS=linux GOARCH=arm64 go build -o app cmd/main.go
  artifacts:
    paths:
      - app
    expire_in: 1 day
  cache:
    key: go-modules
    paths:
      - go/pkg/mod/
  tags:
    - docker

test:
  stage: test
  image: golang:1.24
  script:
    - go test -v ./...
  allow_failure: true
  cache:
    key: go-modules
    paths:
      - go/pkg/mod/
  tags:
    - docker

docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
    - docker push $DOCKER_IMAGE:latest
  dependencies:
    - build
  only:
    - main
    - tags
  tags:
    - docker
